$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = pidof steam || systemctl suspend || loginctl suspend # fuck nvidia

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 180                                # 3min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
    on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}

listener {
    timeout = 420 # 7mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 540 # 9mins
    on-timeout = $suspend_cmd
}
