-- Generated by nwg-displays on 2026-06-24 at 09:13:47. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@120",
    position = "0x0",
    scale = 1.0
})
